
[general]
	#Puts all the added items into a new Every Compat tab instead of their own mod tabs. Be warned that if disabled it could cause some issue with some mods that have custom tabs
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
	#Don't touch unless you are told to
	debug_packet = false

[types]

	[types.leaves_type]

		[types.leaves_type.deeperdarker]
			echo = true

		[types.leaves_type.alexscaves]
			ancient = true

		[types.leaves_type.witherstormmod]
			tainted = true

	[types.wood_type]

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.deeperdarker]
			echo = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.netherdungeons]
			ginger = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.cfm]
			hedge = true

		[entries.leaves_type.mcwfences]
			hedge = true

	[entries.wood_type]

		[entries.wood_type.cfm]
			stripped_kitchen_sink_light = true
			table = true
			kitchen_counter = true
			coffee_table = true
			upgraded_gate = true
			park_bench = true
			stripped_park_bench = true
			cabinet = true
			stripped_kitchen_counter = true
			stripped_table = true
			mail_box = true
			stripped_cabinet = true
			kitchen_drawer = true
			desk = true
			stripped_bedside_cabinet = true
			blinds = true
			desk_cabinet = true
			stripped_kitchen_drawer = true
			stripped_chair = true
			upgraded_fence = true
			crate = true
			chair = true
			stripped_mail_box = true
			stripped_blinds = true
			kitchen_sink_dark = true
			stripped_kitchen_sink_dark = true
			bedside_cabinet = true
			stripped_upgraded_fence = true
			stripped_desk_cabinet = true
			stripped_desk = true
			kitchen_sink_light = true
			stripped_coffee_table = true
			stripped_crate = true
			stripped_upgraded_gate = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.mcwdoors]
			nether_door = true
			stable_head_door = true
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			cottage_door = true
			four_panel_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			beach_door = true
			barn_door = true
			mystic_door = true
			japanese_door = true
			bark_glass_door = true
			classic_door = true
			stable_door = true
			modern_door = true

		[entries.wood_type.mcwtrpdoors]
			ranch_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			beach_trapdoor = true
			swamp_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			glass_trapdoor = true
			barred_trapdoor = true
			blossom_trapdoor = true
			tropical_trapdoor = true
			cottage_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			mystic_trapdoor = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			horse_fence = true
			pyramid_gate = true
			stockade_fence = true
			wired_fence = true

		[entries.wood_type.twigs]
			table = true

